Repository Roave/BetterReflection, pull requests merged in 2018-05, with the labels that each got.

#420 Tidied docs and simply removed weasel words
  README.md
  UPGRADE.md
  docs/ast-extraction.md
  docs/features.md
  docs/find-reflection-on-line.md
  docs/how-it-works.md
  docs/reflection-modification.md
  docs/types.md
  docs/usage.md
Labels: enhancement

#404 Account for case insensitivity
  src/SourceLocator/Ast/Locator.php
  test/unit/SourceLocator/Ast/LocatorTest.php
Labels: needs more info

#422 Build fixes
  src/SourceLocator/Ast/Locator.php
  stub/DateTime.stub
  stub/DateTimeImmutable.stub
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: bug

#410 Updated to PHP-Parser 4
  .travis.yml
  composer.json
  src/NodeCompiler/CompileNodeToValue.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/SourceLocator/Ast/Parser/MemoizingParser.php
  src/SourceLocator/Reflection/SourceStubber.php
  src/TypesFinder/FindParameterType.php
  src/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContext.php
  src/Util/CalculateReflectionColum.php
  src/Util/GetFirstDocComment.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/TypesFinder/FindParameterTypeTest.php
  test/unit/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContextTest.php
  test/unit/Util/CalculateReflectionColumnTest.php
Labels: enhancement

#424 Fixed build
  test/unit/SourceLocator/Ast/Parser/MemoizingParserTest.php
  test/unit/SourceLocator/Type/MemoizingSourceLocatorTest.php
  test/unit/TypesFinder/FindParameterTypeTest.php
  test/unit/TypesFinder/FindPropertyTypeTest.php
  test/unit/TypesFinder/FindReturnTypeTest.php
Labels: enhancement
