Repository Roave/BetterReflection, pull requests merged in 2020-12, with the labels that each got.

#711 Allow non standard `vendor-dir` values when constructing a source locator from a `composer.json`
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir-using-composer-v2/composer.json
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir-using-composer-v2/custom-vendor/a/b/src/ab_PSR-4_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir-using-composer-v2/custom-vendor/composer/installed.json
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/composer.json
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/a/b/src/ab_ClassmapDir/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/a/b/src/ab_ClassmapFile
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/a/b/src/ab_File1.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/a/b/src/ab_File2.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/a/b/src/ab_PSR-0_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/a/b/src/ab_PSR-4_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/composer/installed.json
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/e/f/src/ef_ClassmapDir/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/e/f/src/ef_ClassmapFile
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/e/f/src/ef_File1.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/e/f/src/ef_File2.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/e/f/src/ef_PSR-0_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/custom-vendor/e/f/src/ef_PSR-4_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/src/root_ClassmapDir/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/src/root_ClassmapFile
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/src/root_File1.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/src/root_File2.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/src/root_PSR-0_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir/src/root_PSR-4_Sources/.gitignore
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJsonTest.php
Labels: enhancement

#713 PHP8 - Add support for `mixed` and `static` types
  src/Reflection/Adapter/ReflectionNamedType.php
  src/Reflection/Adapter/ReflectionType.php
  src/Reflection/ReflectionType.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  test/unit/Fixture/PHP8ClassForSourceStubber.php
  test/unit/Fixture/PHP8ClassForSourceStubberExpected.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
Labels: dependencies, enhancement

#716 [BUGFIX] Add custom `vendor-dir` to `MakeLocationForInstalledJson` + Correcting exception messages
  src/SourceLocator/Type/Composer/Factory/Exception/MissingInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  test/unit/SourceLocator/Type/Composer/Factory/Exception/MissingInstalledJsonTest.php
Labels: bug

#719 [BUGFIX] Use `$vendorDir` in `packagePrefixPath` to avoid hardcoded directory
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  test/unit/Assets/ComposerLocators/project-with-custom-vendor-dir-using-composer-v2/composer.json
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerInstalledJsonTest.php
Labels: bug
