Repository Roave/BetterReflection, pull requests merged in 2020-02, with the labels that each got.

#537 various improvements for psalm
  psalm-baseline.xml
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: enhancement

#540 Upgrade reflection-docblock to version ^5.0.0 and upgrade deps
  composer.json
  composer.lock
Labels: dependencies, enhancement

#543 CS fixes
  phpcs.xml.dist
  src/Reflection/Exception/NotAnObject.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionParameter.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/Ast/Locator.php
  src/SourceLocator/Exception/InvalidDirectory.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
Labels: dependencies, enhancement

#544 bump psalm, fix errors, add usePhpDocPropertiesWithoutMagicCall
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml
  src/NodeCompiler/Exception/UnableToCompileNode.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunction.php
  src/Reflection/ReflectionProperty.php
  src/Reflector/ClassReflector.php
  src/TypesFinder/ResolveTypes.php
  src/Util/GetFirstDocComment.php
Labels: dependencies, enhancement

#545 fix CS
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunction.php
  src/Reflector/ClassReflector.php
  src/TypesFinder/ResolveTypes.php
  src/Util/GetFirstDocComment.php
Labels: dependencies, enhancement

#546 Fixed .travis.yml
  .travis.yml
Labels: bug

#547 fix SA
  src/Reflector/ClassReflector.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
Labels: dependencies, enhancement

#548 bump phpbench and phpstan
  .travis.yml
  composer.json
  composer.lock
Labels: dependencies
