Repository Roave/BetterReflection, pull requests merged in 2020-05, with the labels that each got.

#570 Enhancement: Allow fetching constant name from exception
  src/NodeCompiler/Exception/UnableToCompileNode.php
  test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
Labels: enhancement

#572 Align adapter types to ext reflection collection-ish method types
  composer.json
  composer.lock
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Util/GetFirstDocComment.php
Labels: bug

#579 Fixed build
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug

#593 Removed outdated @psalm-suppress
  psalm-baseline.xml
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionObject.php
Labels: enhancement

#592 Fixed PhpStormStubsSourceStubber for classes/functions/constants in namespace
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement

#591 Return system directory separator in adapters
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Util/FileHelper.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionFunctionTest.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Util/FindHelperTest.php
Labels: enhancement

#590 Fixed methods cache in ReflectionClass
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/ClassWithMissingParent.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#589 Fixed ReflectionClass::getMethods() and ::getProperties() in adapter
  src/Reflection/Adapter/ReflectionClass.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
Labels: bug

#587 Fixed ReflectionSourceStubber for unsupported values of default properties
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  test/unit/Fixture/ClassForSourceStubberWithDefaultStaticProperty.php
  test/unit/Fixture/ClassForSourceStubberWithDefaultStaticPropertyExpected.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
Labels: bug

#584 bump phpstan version from 0.12.19 to 0.12.25
  composer.json
  composer.lock
Labels: enhancement

#583 Fixed ReflectionNamedType adapter
  src/Reflection/Adapter/ReflectionNamedType.php
  src/Reflection/Adapter/ReflectionProperty.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
Labels: bug, reflection compatibility

#594 Add hello world github action for #585 to base off
  .github/workflows/build.yml
Labels: enhancement

#586 Fixed ReflectionMethod::isAbstract() in adapter
  src/Reflection/Adapter/ReflectionMethod.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
Labels: bug, reflection compatibility

#595 Psalm.xml cleanup
  psalm.xml
Labels: enhancement

#578 Updated CS
  composer.json
  composer.lock
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: enhancement

#597 ReflectionMethod::isAbstract() should return true for interface methods
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/ReflectionMethod.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: bug

#581 Fixed many traits bugs
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionMethod.php
  test/unit/Fixture/TraitFixture.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#585 Travis is dead, long live GitHub actions
  .gitattributes
  .github/workflows/build.yml
  .scrutinizer.yml
  .travis.yml
  README.md
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: enhancement

#601 Methods are case insensitive, and should be mapped and looked up without considering casing
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/ClassWithCaseInsensitiveMethods.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#602 Fixed hidden bugs
  src/Reflection/ReflectionClass.php
  src/Reflection/StringCast/ReflectionClassConstantStringCast.php
  test/unit/Reflection/ReflectionObjectTest.php
  test/unit/SourceLocator/Type/AnonymousClassObjectSourceLocatorTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: bug

#582 `AutoloadSourceLocator` should support `phar://` paths as well as `file://`
  src/SourceLocator/Type/AutoloadSourceLocator.php
  test/unit/Fixture/BrokenAutoloaderException.php
  test/unit/Fixture/ClassNotInPhar.php
  test/unit/Fixture/autoload.phar
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
Labels: bug

#605 Updated GitHub actions to use `actions/cache@v2` and `shivammathur/setup-php@v2`
  .github/workflows/build.yml
Labels: dependencies, enhancement

#604 #573 ensure `AutoloadSourceLocator` does not interfere with autoloading of PHP-Parser nor BetterReflection internals
  phpcs.xml.dist
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapper.php
  test/unit/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapperTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorWithoutLoadedParserDependenciesTest.php
Labels: bug

#607 Verify `ReflectionSourceStubber` and `PhpInternalSourceLocator` against `FFI`, `memcache`, `mongodb` and `redis` extension symbols
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: dependencies, enhancement

#619 Removed mus-typed docblock annotations
  test/unit/SourceLocator/Type/AnonymousClassObjectSourceLocatorTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
Labels: enhancement

#609 Exclude PhpStormStubsSourceStubber temporarily from the PHPStan analysis
  phpstan.neon
Labels: bug, dependencies

#610 Fixed `ReflectionClass::isInstance()` adapter compatibility with native reflection
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionObject.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
Labels: bug

#618 PhpStormStubsSourceStubber fixes for case-insensitive classes/functions/constants
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug, dependencies

#622 TRUE, FALSE, NULL constant names compatible with PHP
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: dependencies, enhancement

#621 Annotations cleanup
  phpcs.xml.dist
  src/NodeCompiler/CompileNodeToValue.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapper.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  src/SourceLocator/Type/Composer/Psr/PsrAutoloaderMapping.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerInstalledJsonTest.php
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJsonTest.php
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
Labels: enhancement

#606 #599 add infection (mutation testing) to test runs
  .github/workflows/benchmarks.yml
  .github/workflows/build.yml
  .github/workflows/coding-standards.yml
  .github/workflows/compatibility.yml
  .github/workflows/demo-scripts.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  README.md
  composer.json
  composer.lock
  infection.json.dist
  src/SourceLocator/Ast/Parser/MemoizingParser.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapper.php
  test/unit/SourceLocator/Ast/Parser/MemoizingParserTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapperTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
Labels: dependencies, enhancement

#630 Removed duplicate ReflectionSourceStubber::addParameterModifiers() call
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
Labels: enhancement

#629 Fixed ReflectionClass::getReflectionConstant() in adapter for non-existent constant
  src/Reflection/Adapter/ReflectionClass.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
Labels: bug
