Repository Roave/BetterReflection, pull requests merged in 2020-07, with the labels that each got.

#677 Bump vimeo/psalm from 3.11.2 to 3.12.1
  composer.json
  composer.lock
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  src/SourceLocator/Type/FileIteratorSourceLocator.php
Labels: dependencies, enhancement

#674 Fix Adapter\ReflectionClass::$name
  src/Reflection/Adapter/ReflectionClass.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
Labels: bug

#660 Allow functions to be deprecated
  src/Reflection/ReflectionFunctionAbstract.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
Labels: enhancement

#678 ReflectionParameter: try to get the correct default value for constants
  src/Reflection/ReflectionParameter.php
  test/unit/Reflection/ReflectionParameterTest.php
Labels: enhancement
