Repository Roave/BetterReflection, pull requests merged in 2020-01, with the labels that each got.

#516 Run PHPStan without memory limit
  .travis.yml
Labels: bug, dependencies

#518 Run CI only once on PR from another branch of the repo
  .travis.yml
Labels: dependencies, enhancement

#520 Bump jetbrains/phpstorm-stubs from 2019.2 to 2019.3
  composer.json
  composer.lock
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: dependencies, enhancement

#517 Bump psalm to 3.8.2
  .gitattributes
  .travis.yml
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml
  src/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContext.php
Labels: dependencies, enhancement

#524 Speedup code coverage generation by using xdebug filter
  .travis.yml
Labels: enhancement

#521 Travis improvements
  .travis.yml
  phpcs.xml.dist
Labels: dependencies, enhancement

#523 ReflectionClass::getConstructor() should work event if the constructor isn't the first method in the class
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflector/ClassReflectorTest.php
Labels: bug

#522 Fixed deprecated warning in ReflectionSourceStubber
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
Labels: bug

#526 Improve Psalm coverage for decoded datas from json files
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
Labels: enhancement

#527 CS fix
  composer.json
  composer.lock
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
Labels: bug, dependencies

#529 Fix dependencies installation
  composer.lock
Labels: bug, dependencies

#528 Added ReflectionNamedType adapter
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionNamedType.php
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/ReflectionType.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
Labels: bug, enhancement

#531 add psalm types
  psalm.xml
  src/NodeCompiler/CompileNodeToValue.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Exception/NotAnObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/StringCast/ReflectionClassConstantStringCast.php
  src/Reflection/StringCast/ReflectionConstantStringCast.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/Ast/Locator.php
  src/SourceLocator/Exception/InvalidDirectory.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Psr/PsrAutoloaderMapping.php
Labels: enhancement, reflection compatibility

#532 fix windows path to linux + phpcbf
  psalm.xml
  src/NodeCompiler/CompileNodeToValue.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/StringCast/ReflectionConstantStringCast.php
Labels: bug

#533 Add compatibility with Composer v2 installed.json files
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  test/unit/Assets/ComposerLocators/project-using-composer-v2/composer.json
  test/unit/Assets/ComposerLocators/project-using-composer-v2/vendor/a/b/src/ab_PSR-4_Sources/.gitignore
  test/unit/Assets/ComposerLocators/project-using-composer-v2/vendor/composer/installed.json
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerInstalledJsonTest.php
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJsonTest.php
Labels: enhancement

#534 Show our type coverage
  .travis.yml
  README.md
Labels: enhancement
