Repository Roave/BetterReflection, pull requests merged in 2021-11, with the labels that each got.

#833 Bump phpstan/phpstan to 1.0.0
  .github/workflows/phpstan.yml
  composer.json
  composer.lock
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionObject.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  src/SourceLocator/Type/EvaledCodeSourceLocator.php
Labels: enhancement, dependencies

#834 Fix parameters used when instantiating a reflector in code examples/docs
  docs/usage.md
Labels: bug

#835 Improved detection of supported functions in `PhpStormStubsSourceStubber` based on `JetBrains\PhpStorm\Internal\PhpStormStubsElementAvailable` attribute to decide supported PHP versions
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement

#837 Bump phpstan/phpstan to 1.1.1
  composer.json
  composer.lock
  phpstan.neon
  src/Reflection/ReflectionFunctionAbstract.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  stubs/enum_exists.php
Labels: enhancement

#836 Added `ReflectionNamedType::getClass()`
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionEnum.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionIntersectionType.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionNamedType.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/ReflectionType.php
  src/Reflection/ReflectionUnionType.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
Labels: enhancement

#839 Improved code coverage for reflections
  infection.json.dist
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionIntersectionType.php
  src/Reflection/ReflectionNamedType.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionType.php
  src/Reflection/StringCast/ReflectionClassStringCast.php
  src/Reflection/StringCast/ReflectionMethodStringCast.php
  test/unit/Fixture/StaticProperties.php
  test/unit/Fixture/StaticPropertyGetSet.php
  test/unit/Fixture/StringCastMethods.php
  test/unit/Reflection/ReflectionAttributeTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionConstantTest.php
  test/unit/Reflection/ReflectionEnumCaseTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionIntersectionTypeTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionUnionTypeTest.php
  test/unit/Reflection/StringCast/ReflectionFunctionStringCastTest.php
  test/unit/Reflection/StringCast/ReflectionMethodStringCastTest.php
Labels: enhancement

#840 Use native `assert()` instead of `Webmozart\Assert\Assert`, which is not an explicit dependency
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionProperty.php
Labels: bug

#842 Improved mutation score, reject invalid flags when retrieving attributes
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionEnumBackedCase.php
  src/Reflection/Adapter/ReflectionEnumUnitCase.php
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionMethod.php
  src/SourceLocator/Ast/Exception/ParseToAstFailure.php
  src/SourceLocator/Ast/Parser/MemoizingParser.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/Type/MemoizingSourceLocator.php
  test/unit/Fixture/DefaultProperties.php
  test/unit/Fixture/InheritedClassProperties.php
  test/unit/Fixture/StaticProperties.php
  test/unit/Fixture/StringCastAttributes.php
  test/unit/Fixture/StringCastParameters.php
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumBackedCaseTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionEnumUnitCaseTest.php
  test/unit/Reflection/Adapter/ReflectionFunctionTest.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/Adapter/ReflectionParameterTest.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/Exception/InvalidArrowFunctionBodyNodeTest.php
  test/unit/Reflection/Exception/InvalidConstantNodeTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Reflection/StringCast/ReflectionAttributeStringCastTest.php
  test/unit/Reflection/StringCast/ReflectionParameterStringCastTest.php
  test/unit/SourceLocator/Ast/Exception/ParseToAstFailureTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement, reflection compatibility

#838 `ReflectionMethod` and `ReflectionFunction` no longer extend `ReflectionFunctionAbstract`
  docs/usage.md
  src/Identifier/Identifier.php
  src/NodeCompiler/CompilerContext.php
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunction.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionParameter.php
  src/TypesFinder/FindParameterType.php
  src/TypesFinder/FindReturnType.php
  test/unit/Identifier/IdentifierTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/TypesFinder/FindParameterTypeTest.php
  test/unit/TypesFinder/FindReturnTypeTest.php
Labels: enhancement, BC break

#843 Increased minimum mutation score to 94%
  infection.json.dist
  phpunit.xml.dist
  src/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapper.php
Labels: enhancement

#844 Fixed `AutoloadSourceLocatorTest::testCanAutoloadPsr4ClassesInPotentiallyMultipleDirectories()` autoloading of PHPUnit assertion classes
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
Labels: bug

#845 Updated dependencies
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml
Labels: enhancement, dependencies

#846 Automating dependency upgrades and merges thereof
  .github/dependabot.yml
  .github/workflows/merge-dependabot-upgrades.yml
Labels: enhancement

#847 Improved detection if parameter is optional
  phpstan.neon
  psalm.xml
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
Labels: enhancement

#848 Less ignored errors in Psalm
  psalm.xml
  src/BetterReflection.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionNamedType.php
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionEnumCase.php
  src/Reflection/ReflectionFunction.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#849 Don't ignore Psalm `PossiblyNullArgument` errors anymore
  psalm.xml
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompilerContext.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/StringCast/ReflectionClassStringCast.php
  src/Reflection/StringCast/ReflectionConstantStringCast.php
  src/Reflection/StringCast/ReflectionFunctionStringCast.php
  src/Reflection/StringCast/ReflectionMethodStringCast.php
  src/SourceLocator/Ast/Exception/ParseToAstFailure.php
  src/SourceLocator/Ast/Locator.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/ClosureSourceLocator.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  src/SourceLocator/Type/PhpInternalSourceLocator.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
  test/unit/Reflection/StringCast/ReflectionConstantStringCastTest.php
  test/unit/Reflection/StringCast/ReflectionFunctionStringCastTest.php
  test/unit/SourceLocator/Ast/LocatorTest.php
Labels: enhancement

#850 Don't ignore Psalm `NullableReturnStatement` and `InvalidNullableReturnType` errors anymore
  psalm.xml
  src/NodeCompiler/CompilerContext.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionNamedType.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#851 Don't ignore Psalm `MoreSpecificReturnType` and `LessSpecificReturnStatement` errors anymore
  psalm.xml
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflector/DefaultReflector.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContext.php
Labels: enhancement

#852 Improved mutation score
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/Type/MemoizingSourceLocator.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/Util/CalculateReflectionColumnTest.php
Labels: enhancement

#854 No more Psalm baseline
  infection.json.dist
  psalm-baseline.xml
  psalm.xml
  src/Reflection/ReflectionParameter.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/DirectoriesSourceLocator.php
Labels: enhancement

#853 Infection should skip initial tests because we already provide coverage
  .github/workflows/mutation-tests.yml
Labels: enhancement

#855 Split PhpStormStubs caching visitor to separate class
  phpstan.neon
  src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement

#857 Run coverage and mutation tests all at once
  .github/workflows/mutation-tests.yml
  infection.json.dist
Labels: enhancement, dependencies

#858 Removed dead condition
  src/SourceLocator/Ast/FindReflectionsInTree.php
Labels: enhancement

#860 Small code improvements
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/MemoizingSourceLocator.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
  test/unit/SourceLocator/Type/EvaledCodeSourceLocatorTest.php
Labels: enhancement

#862 Fixed "Auto-merge Dependabot PRs" workflow
  .github/workflows/merge-dependabot-upgrades.yml
Labels: enhancement

#863 Just another try to fix of "Auto-merge Dependabot PRs" workflow
  .github/workflows/merge-dependabot-upgrades.yml
Labels: enhancement

#866 Try to fix auto-merge for dependatbot PR's
  .github/workflows/merge-dependabot-upgrades.yml
Labels: bug

#867 Try to fix the "Auto-merge Dependabot PRs" workflow again
  .github/workflows/benchmarks.yml
  .github/workflows/coding-standards.yml
  .github/workflows/compatibility.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/demo-scripts.yml
  .github/workflows/merge-dependabot-upgrades.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: enhancement

#875 Fixed parsing of `PhpStormStubsElementAvailable` in `PhpStormStubsSourceStubber`
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug, dependencies

#874 Always require PHP version for `PhpStormStubsSourceStubber` - `PHP_VERSION_ID` as default
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/Reflection/StringCast/ReflectionClassStringCastTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement, dependencies

#879 Fixed type of `value` property for integer backed enum
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#881 Fixed parameter and return types of default enum methods
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#876 jetbrains/phpstorm-stubs 2021.3
  composer.json
  composer.lock
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/Reflection/StringCast/ReflectionMethodStringCastTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement

#882 No need to force PHP version update anymore
  .github/workflows/continuous-integration.yml
Labels: enhancement, dependencies, php

#883 Support promoted properties docblocks and attributes
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/Attributes.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement, reflection compatibility

#885 .editorconfig
  .editorconfig
  .gitattributes
Labels: enhancement

#880 Promoted property with a default value does not have a default value - the default value is on the parameter only
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: bug

#893 Bump nikic/php-parser to 4.13.2
  composer.json
  composer.lock
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
Labels: enhancement, dependencies
