Repository Roave/BetterReflection, pull requests merged in 2021-09, with the labels that each got.

#755 Narrower types for reflection functions and internal source stubber logic
  psalm-baseline.xml
  src/Reflection/Exception/InvalidAbstractFunctionNodeType.php
  src/Reflection/ReflectionFunction.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionMethod.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContext.php
  test/unit/Reflection/Exception/InvalidAbstractFunctionNodeTypeTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
Labels: enhancement, BC break

#756 Fixed parsing closures with types in namespace
  src/SourceLocator/Type/ClosureSourceLocator.php
  test/unit/Reflection/ReflectionFunctionTest.php
Labels: bug

#759 Removed support of PHP4 style constructors
  UPGRADE.md
  src/Reflection/ReflectionMethod.php
  test/unit/Fixture/Php4StyleCaseInsensitiveConstruct.php
  test/unit/Fixture/Php4StyleConstruct.php
  test/unit/Fixture/Php4StyleConstructInNamespace.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: enhancement, BC break

#757 Support of arrow functions
  phpstan.neon
  psalm-baseline.xml
  src/Reflection/Exception/InvalidArrowFunctionBodyNode.php
  src/Reflection/ReflectionFunction.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/SourceLocator/Ast/Strategy/NodeToReflection.php
  src/SourceLocator/Type/ClosureSourceLocator.php
  test/unit/Fixture/ArrowFunctionInNamespace.php
  test/unit/Fixture/ArrowFunctionNoNamespace.php
  test/unit/Reflection/Exception/InvalidArrowFunctionBodyNodeTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionFunctionTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
Labels: enhancement

#762 Trait case sensitivity and aliasing collision fixes
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#763 expand `CompileNodeToValue` to support magic constants in functions, traits and constant declarations
  UPGRADE.md
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompilerContext.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/Fixture/MagicConstants.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/NodeCompiler/CompilerContextTest.php
  test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
Labels: enhancement

#765 Adapter ReflectionProperty: Added hasDefaultValue() and getDefaultValue()
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionProperty.php
  test/unit/Fixture/DefaultProperties.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#766 Reduce `CompilerContext` API to avoid temporal coupling of method calls
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompilerContext.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  test/unit/NodeCompiler/CompilerContextTest.php
Labels: enhancement

#764 It's possible to get default parameter value for internal methods/functions in PHP 8
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
Labels: enhancement

#768 Bump phpdocumentor/type-resolver to 1.5.0
  composer.json
  composer.lock
Labels: enhancement, dependencies

#770 Implemented `Stringable` interface
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement

#771 By default, configure PHP-Parser to always consider sources as if they were PHP 7+
  src/BetterReflection.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorWithoutLoadedParserDependenciesTest.php
Labels: enhancement, BC break

#769 Added all missing methods to adapters and fixed tests
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/Adapter/ReflectionProperty.php
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionFunctionTest.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/Adapter/ReflectionParameterTest.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
Labels: enhancement

#774 remove expired "extra" field in composer.json
  composer.json
  composer.lock
Labels: enhancement, dependencies

#775 Updated dependencies
  composer.json
  composer.lock
Labels: dependencies

#777 Use `is_file()` instead of `file_exists()` because we really need to check only files
  test/unit/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapperTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
  test/unit/Util/Autoload/ClassLoaderMethod/FileCacheLoaderTest.php
Labels: enhancement

#778 Make sure that `PhpStormStubsSourceStubber` updates constants based on current runtime environment, when outdated or not defined in stubs
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/Fixture/FakeConstants.php
  test/unit/Fixture/FakeConstantsStub.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug, enhancement

#782 More tests for anonymous classes inheritance reflection
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug, enhancement

#781 Removed dead code / unused psalm error suppressions
  psalm.xml
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionConstant.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/Reflection/ReflectionObjectTest.php
Labels: enhancement

#780 Properties types are rendered by `ReflectionProperty#__toString()`
  UPGRADE.md
  src/Reflection/StringCast/ReflectionPropertyStringCast.php
  test/unit/Fixture/StringCastClass.php
  test/unit/Fixture/StringCastClassExpected.txt
  test/unit/Fixture/StringCastProperties.php
  test/unit/Reflection/StringCast/ReflectionPropertyStringCastTest.php
Labels: enhancement

#783 Use `is_file()` instead of `file_exists()` when we need to be sure that the checked locations are files, and not directories
  src/SourceLocator/Exception/InvalidDirectory.php
  src/SourceLocator/FileChecker.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  src/SourceLocator/Type/Composer/PsrAutoloaderLocator.php
  src/SourceLocator/Type/EvaledCodeSourceLocator.php
  src/Util/Autoload/ClassLoaderMethod/FileCacheLoader.php
  test/unit/SourceLocator/FileCheckerTest.php
Labels: enhancement

#784 Types, tests, cleanup and code coverage
  psalm-baseline.xml
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/Ast/Strategy/AstConversionStrategy.php
  src/SourceLocator/Ast/Strategy/NodeToReflection.php
  src/SourceLocator/Exception/NoAnonymousClassOnLine.php
  src/SourceLocator/Exception/NoClosureOnLine.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
  src/SourceLocator/Type/ClosureSourceLocator.php
  src/TypesFinder/FindParameterType.php
  src/Util/FindReflectionOnLine.php
  test/unit/Assets/ComposerLocators/project-without-composer.json/.gitignore
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflector/ClassReflectorTest.php
  test/unit/Reflector/ConstantReflectorTest.php
  test/unit/Reflector/FunctionReflectorTest.php
  test/unit/SourceLocator/Ast/FindReflectionsInTreeTest.php
  test/unit/SourceLocator/Ast/Strategy/NodeToReflectionTest.php
  test/unit/SourceLocator/Exception/NoAnonymousClassOnLineTest.php
  test/unit/SourceLocator/Exception/NoClosureOnLineTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
  test/unit/SourceLocator/Type/AbstractSourceLocatorTest.php
  test/unit/SourceLocator/Type/AnonymousClassObjectSourceLocatorTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
  test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerInstalledJsonTest.php
  test/unit/SourceLocator/Type/ComposerSourceLocatorTest.php
  test/unit/SourceLocator/Type/EvaledCodeSourceLocatorTest.php
  test/unit/SourceLocator/Type/FileIteratorSourceLocatorTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
  test/unit/TypesFinder/FindParameterTypeTest.php
  test/unit/TypesFinder/ResolveTypesTest.php
Labels: enhancement

#752 Split `ReflectionType` into `ReflectionNamedType|ReflectionNamedType` in parameter and return types
  src/Reflection/Adapter/ReflectionType.php
  src/Reflection/Adapter/ReflectionUnionType.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/ReflectionType.php
  src/Reflection/ReflectionUnionType.php
  test/unit/Reflection/Adapter/ReflectionFunctionTest.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/Adapter/ReflectionParameterTest.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
Labels: enhancement, BC break

#785 Promoted properties support
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Fixture/ExampleClassExport.txt
  test/unit/Fixture/Methods.php
  test/unit/Reflection/Adapter/ReflectionParameterTest.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement, reflection compatibility

#786 Implemented `ReflectionProperty#isInitialized()`
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionProperty.php
  test/unit/Fixture/InitializedProperties.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement, reflection compatibility

#788 Simplified `CompilerContext` internals, making it compatible with more reflection symbols
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompilerContext.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/NodeCompiler/CompilerContextTest.php
  test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
Labels: enhancement
