Repository Roave/BetterReflection, pull requests merged in 2021-12, with the labels that each got.

#895 Fixed missing assigment in `FileIteratorSourceLocator`
  src/SourceLocator/Type/FileIteratorSourceLocator.php
Labels: enhancement

#897 Removed traling spaces
  test/unit/Fixture/AutoloadableClassWithTwoDirectories.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionConstantTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#903 Bump vimeo/psalm to 4.14.0
  composer.json
  composer.lock
  src/SourceLocator/Type/DirectoriesSourceLocator.php
Labels: enhancement, dependencies

#900 Removed doc blocks parsing support
  README.md
  UPGRADE.md
  composer.json
  composer.lock
  demo/basic-reflection/example3.php
  demo/parsing-whole-directory/example1.php
  demo/parsing-whole-directory/example2.php
  docs/features.md
  docs/how-it-works.md
  docs/types.md
  src/Reflection/Annotation/AnnotationHelper.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/TypesFinder/FindParameterType.php
  src/TypesFinder/FindPropertyType.php
  src/TypesFinder/FindReturnType.php
  src/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContext.php
  src/TypesFinder/ResolveTypes.php
  test/benchmark/PhpUnitTestCaseBench.php
  test/compat/ResolveDocblockTypes.phpt
  test/demo/check-demo.sh
  test/unit/Reflection/Annotation/AnnotationHelperTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionFunctionTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/TypesFinder/FindParameterTypeTest.php
  test/unit/TypesFinder/FindPropertyTypeTest.php
  test/unit/TypesFinder/FindReturnTypeTest.php
  test/unit/TypesFinder/PhpDocumentor/NamespaceNodeToReflectionTypeContextTest.php
  test/unit/TypesFinder/ResolveTypesTest.php
Labels: enhancement, BC break, dependencies

#898 We should add `Stringable` interface only when it can be reflected
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement

#907 Revert "Removed support for PHP4 style constructors"
  UPGRADE.md
  src/Reflection/ReflectionMethod.php
  test/unit/Fixture/Php4StyleCaseInsensitiveConstruct.php
  test/unit/Fixture/Php4StyleConstruct.php
  test/unit/Fixture/Php4StyleConstructInNamespace.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: enhancement

#906 Added some missing return type hints
  src/SourceLocator/Type/AggregateSourceLocator.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
  src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
  test/unit/SourceLocator/Type/MemoizingSourceLocatorTest.php
Labels: enhancement

#905 Support `resource` as constant value, make `STDIN`, `STDOUT` and `STDERR` stubs actual `resource`s
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompiledValue.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/Util/ConstantNodeChecker.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
  test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
  test/unit/Util/ConstantNodeCheckerTest.php
Labels: enhancement, BC break

#908 Removed the ability to monkey patch the code
  README.md
  UPGRADE.md
  demo/monkey-patching/MyClass.php
  demo/monkey-patching/index.php
  docs/features.md
  docs/how-it-works.md
  docs/reflection-modification.md
  docs/usage.md
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/compat/MonkeyPatchFunction.phpt
  test/demo/check-demo.sh
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement, BC break

#910 `PhpStormStubsSourceStubber` should add uses from current namespace to the stub
  src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug

#918 Fixed adapter `ReflectionClassConstant::getValue()` for enum cases
  src/Reflection/Adapter/ReflectionClassConstant.php
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
Labels: bug

#921 Update features.md
  docs/features.md
Labels: enhancement

#923 Enum can implement interface
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/Enums.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#926 Use composer 2.1 for tests temporarily
  .github/workflows/continuous-integration.yml
Labels: enhancement, dependencies

#924 Simplified `continuous-integration.yml` with `ramsey/composer-install@v2`
  .github/workflows/continuous-integration.yml
Labels: enhancement, dependencies

#922 Add `ReflectionFunctionAbstract::couldThrow()`
  src/Reflection/ReflectionFunctionAbstract.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
Labels: enhancement

#931 Revert "Use composer 2.1 for tests temporarily"
  .github/workflows/continuous-integration.yml
Labels: enhancement, dependencies, php
