Repository Roave/BetterReflection, pull requests merged in 2022-10, with the labels that each got.

#1265 Stringable interface does not implement Stringable
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#1269 Fixed detection of interface circular reference
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#1270 Optimisation of getting methods, properties and constants from interfaces
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/InheritedClassConstants.php
  test/unit/Fixture/InheritedClassMethods.php
Labels: enhancement

#1266 Optimisations of getting methods, properties and constants in `ReflectionClass`
  src/Reflection/ReflectionClass.php
Labels: enhancement

#1273 Fixed Covered Code MSI percentage
  src/Reflection/ReflectionClass.php
  src/SourceLocator/Ast/Strategy/NodeToReflection.php
  test/unit/Fixture/InheritedClassMethods.php
  test/unit/Fixture/InheritedClassProperties.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/StringCast/ReflectionClassStringCastTest.php
Labels: enhancement

#1284 Kill the last mutant in `ReflectionClass::getProperties()`
  test/unit/Fixture/InheritedClassProperties.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement

#1285 `Reflection*::getStartLine()/getEndLine()/getStartColumn()/getEndColumn()` throws `\Roave\BetterReflection\Reflection\Exception\CodeLocationMissing` instead of `\RuntimeException`
  src/Reflection/Exception/CodeLocationMissing.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/Reflection/Exception/CodeLocationMissingTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#1286 Fixed reflection compatibility when method/property/constant/case name is empty
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
Labels: bug, reflection compatibility

#1298 Optimized `ReflectionClass::getName()` for anonymous classes
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/AnonymousClassInstanceWithParentDefinedLater.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement
