Repository Roave/BetterReflection, pull requests merged in 2022-01, with the labels that each got.

#941 ReflectionNamedType with mixed allows null
  src/Reflection/Adapter/ReflectionNamedType.php
  src/Reflection/Adapter/ReflectionType.php
  src/Reflection/ReflectionNamedType.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
Labels: bug

#942 Fix trait method visibility change leaking into other traits
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#945 Fix and update PHPStan to `1.3.x`
  composer.json
  composer.lock
Labels: enhancement, dependencies

#947 Child class should have renamed trait method from parent
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#956 Main branch is 5.1.x
  .github/workflows/continuous-integration.yml
  README.md
  infection.json.dist
Labels: enhancement

#959 Added `false` to types considered by `ReflectionNamedType#isBuiltIn()` logic
  src/Reflection/ReflectionNamedType.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
Labels: bug

#962 `static`, `self` and `parent` are not built-in in ReflectionNamedType adapter
  src/Reflection/Adapter/ReflectionNamedType.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
Labels: bug

#965 Fixed located source for parent methods and methods from traits
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: bug

#972 Improved `PhpStormStubsSourceStubber` for PHP < 8.0
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug, enhancement

#971 Fix missing properties for `UnitEnum` and `BackedEnum` interfaces
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: bug, enhancement

#973 Improved mutation score
  src/Reflection/StringCast/ReflectionClassConstantStringCast.php
  src/Reflection/StringCast/ReflectionConstantStringCast.php
  src/SourceLocator/Type/Composer/Psr/Psr0Mapping.php
  src/SourceLocator/Type/Composer/Psr/Psr4Mapping.php
  src/SourceLocator/Type/Composer/PsrAutoloaderLocator.php
  src/Util/CalculateReflectionColumn.php
  test/unit/Fixture/FindReflectionOnLineFixture.php
  test/unit/Fixture/StringCastClassObject.php
  test/unit/Fixture/StringCastClassObjectExpected.txt
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/StringCast/ReflectionTypeStringCastTest.php
  test/unit/SourceLocator/Located/LocatedSourceTest.php
  test/unit/SourceLocator/Type/Composer/Psr/Psr4MappingTest.php
  test/unit/SourceLocator/Type/Composer/PsrAutoloaderLocatorTest.php
  test/unit/SourceLocator/Type/SingleFileSourceLocatorTest.php
  test/unit/Util/Autoload/ClassLoaderTest.php
  test/unit/Util/CalculateReflectionColumnTest.php
  test/unit/Util/ConstantNodeCheckerTest.php
  test/unit/Util/FindReflectionOnLineTest.php
  test/unit/Util/Visitor/ReturnNodeVisitorTest.php
Labels: enhancement

#975 Added `ReflectionType::getOwner()`
  src/Reflection/ReflectionType.php
  test/unit/Reflection/ReflectionIntersectionTypeTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionUnionTypeTest.php
Labels: enhancement

#980 Mark ClassLoader as deprecated
  src/Util/Autoload/ClassLoader.php
Labels: enhancement

#982 Mark `Roave\BetterReflection\Util\Autoload` as deprecated
  src/Util/Autoload/ClassLoader.php
  src/Util/Autoload/ClassLoaderMethod/EvalLoader.php
  src/Util/Autoload/ClassLoaderMethod/Exception/SignatureCheckFailed.php
  src/Util/Autoload/ClassLoaderMethod/FileCacheLoader.php
  src/Util/Autoload/ClassLoaderMethod/LoaderMethodInterface.php
  src/Util/Autoload/ClassPrinter/ClassPrinterInterface.php
  src/Util/Autoload/ClassPrinter/PhpParserPrinter.php
  src/Util/Autoload/Exception/ClassAlreadyLoaded.php
  src/Util/Autoload/Exception/ClassAlreadyRegistered.php
  src/Util/Autoload/Exception/FailedToLoadClass.php
Labels: enhancement

#983 Improved mutation score
  infection.json.dist
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/ClosureSourceLocator.php
  src/SourceLocator/Type/EvaledCodeSourceLocator.php
  src/Util/Autoload/ClassLoader.php
  src/Util/ClassExistenceChecker.php
  src/Util/FileHelper.php
  test/unit/Fixture/AnonymousClassExtendingClassFromNamespace.php
  test/unit/Fixture/ClosureWithParameterWithClassFromNamespace.php
  test/unit/Fixture/InheritedClassConstants.php
  test/unit/Fixture/InheritedClassProperties.php
  test/unit/Fixture/InitializedProperties.php
  test/unit/Fixture/Methods.php
  test/unit/Fixture/TraitWithAbstractMethod.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/SourceLocator/Type/AnonymousClassObjectSourceLocatorTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
  test/unit/Util/ClassExistenceCheckerTest.php
Labels: enhancement
