Repository Roave/BetterReflection, pull requests merged in 2022-09, with the labels that each got.

#1192 PHP 8.2: Support for `readonly` classes
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionObject.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflector/DefaultReflectorTest.php
Labels: enhancement

#1197 PHP 8.2: Support for standalone `null` type
  src/Reflection/Adapter/ReflectionNamedType.php
  src/Reflection/ReflectionNamedType.php
  src/Reflection/ReflectionType.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/Reflection/StringCast/ReflectionTypeStringCastTest.php
Labels: enhancement

#1196 PHP 8.2: Support for fetching properties of `enum`s in `const` expressions
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
Labels: enhancement

#1191 Basic support for PHP 8.2
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  test/unit/Fixture/DefaultProperties.php
  test/unit/Fixture/RuntimeProperties.php
  test/unit/Fixture/StringCastClassObject.php
  test/unit/Fixture/StringCastClassObjectExpected.txt
  test/unit/Reflection/Adapter/ReflectionFunctionTest.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement, dependencies

#1205 PHP 8.2: Constants in traits
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  test/unit/Fixture/ClassesWithConstants.php
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
Labels: enhancement, reflection compatibility

#1142 Removed deprecated `Util\Autoload`
  src/Util/Autoload/ClassLoader.php
  src/Util/Autoload/ClassLoaderMethod/EvalLoader.php
  src/Util/Autoload/ClassLoaderMethod/Exception/SignatureCheckFailed.php
  src/Util/Autoload/ClassLoaderMethod/FileCacheLoader.php
  src/Util/Autoload/ClassLoaderMethod/LoaderMethodInterface.php
  src/Util/Autoload/ClassPrinter/ClassPrinterInterface.php
  src/Util/Autoload/ClassPrinter/PhpParserPrinter.php
  src/Util/Autoload/Exception/ClassAlreadyLoaded.php
  src/Util/Autoload/Exception/ClassAlreadyRegistered.php
  src/Util/Autoload/Exception/FailedToLoadClass.php
  test/unit/Util/Autoload/ClassLoaderMethod/EvalLoaderTest.php
  test/unit/Util/Autoload/ClassLoaderMethod/Exception/SignatureCheckFailedTest.php
  test/unit/Util/Autoload/ClassLoaderMethod/FileCacheLoaderTest.php
  test/unit/Util/Autoload/ClassLoaderTest.php
  test/unit/Util/Autoload/ClassPrinter/PhpParserPrinterTest.php
  test/unit/Util/Autoload/Exception/ClassAlreadyLoadedTest.php
  test/unit/Util/Autoload/Exception/ClassAlreadyRegisteredTest.php
  test/unit/Util/Autoload/Exception/FailedToLoadClassTest.php
Labels: enhancement, BC break

#1141 Removed useleses method `ReflectionProperty::isAccessible()` in adapter
  src/Reflection/Adapter/ReflectionProperty.php
Labels: enhancement, BC break

#1138 `StringSourceLocator` is forced to be built with a `non-empty-string`
  src/SourceLocator/Exception/EmptyPhpSourceCode.php
  src/SourceLocator/Type/StringSourceLocator.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionConstantTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/SourceLocator/Type/StringSourceLocatorTest.php
Labels: enhancement, BC break

#1140 Reflection types cleanup
  src/Reflection/ReflectionIntersectionType.php
  src/Reflection/ReflectionNamedType.php
  src/Reflection/ReflectionType.php
  src/Reflection/ReflectionUnionType.php
  test/unit/Reflection/ReflectionIntersectionTypeTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/Reflection/ReflectionUnionTypeTest.php
Labels: enhancement, BC break

#1139 `ReflectionEnum::__construct()` can be private
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionEnum.php
Labels: enhancement, BC break

#1198 PHP 8.2: Support for disjunctive normal form types
  src/Reflection/Adapter/ReflectionIntersectionType.php
  src/Reflection/Adapter/ReflectionType.php
  src/Reflection/Adapter/ReflectionUnionType.php
  src/Reflection/ReflectionIntersectionType.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionUnionType.php
  src/Reflection/StringCast/ReflectionTypeStringCast.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  stubs/ReflectionIntersectionType.php
  test/unit/Reflection/Adapter/ReflectionIntersectionTypeTest.php
  test/unit/Reflection/Adapter/ReflectionUnionTypeTest.php
  test/unit/Reflection/ReflectionUnionTypeTest.php
  test/unit/Reflection/StringCast/ReflectionTypeStringCastTest.php
Labels: enhancement, BC break

#1209 `ReflectionParameter::getClass()`, `ReflectionParameter::isArray()` and `ReflectionParameter::isCallable()` implementations moved only to adapter
  src/Reflection/Adapter/ReflectionParameter.php
  src/Reflection/ReflectionParameter.php
  test/unit/Fixture/Methods.php
  test/unit/Reflection/Adapter/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionFunctionTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
Labels: enhancement, BC break

#1213 Removed `ReflectionParameter::getAst()` to prevent memory leaks
  src/Reflection/Attribute/ReflectionAttributeHelper.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionEnumCase.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/Reflection/Attribute/ReflectionAttributeHelperTest.php
  test/unit/Reflection/ReflectionParameterTest.php
Labels: enhancement, BC break

#1214 Removed some node references to prevent memory leaks
  src/Reflection/ReflectionAttribute.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionEnumCase.php
  src/Reflection/ReflectionParameter.php
  src/Util/CalculateReflectionColumn.php
  test/unit/Reflection/ReflectionConstantTest.php
  test/unit/Reflection/ReflectionEnumCaseTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/SourceLocator/Ast/Strategy/NodeToReflectionTest.php
Labels: enhancement, BC break

#1216 Removed `ReflectionProperty::getAst()` to prevent memory leaks
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionProperty.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement, BC break

#1220 Improved mutation score
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionProperty.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Fixture/ExampleClassExport.txt
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#1221 Improved mutation score
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompilerContext.php
  src/Reflection/ReflectionAttribute.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionIntersectionType.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/ReflectionUnionType.php
  src/SourceLocator/Ast/Exception/ParseToAstFailure.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Fixture/ExampleClassExport.txt
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/SourceLocator/Ast/Exception/ParseToAstFailureTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
Labels: enhancement

#1219 `Reflection*::getNamespaceName()` returns null when no namespace - namespace as empty string is implemented only in adapters
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/CompilerContext.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionObject.php
  test/unit/NodeCompiler/CompilerContextTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionConstantTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionFunctionTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
Labels: enhancement, BC break

#1224 `Reflection*::getDocComment()` returns null when no doc comment
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionEnumBackedCase.php
  src/Reflection/Adapter/ReflectionEnumUnitCase.php
  src/Reflection/Adapter/ReflectionFunction.php
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/Annotation/AnnotationHelper.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionEnumCase.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionProperty.php
  src/Util/GetLastDocComment.php
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumBackedCaseTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionEnumUnitCaseTest.php
  test/unit/Reflection/Adapter/ReflectionFunctionTest.php
  test/unit/Reflection/Adapter/ReflectionMethodTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/Adapter/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionEnumCaseTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Util/GetLastDocCommentTest.php
Labels: enhancement, BC break

#1223 Added methods to get value expression
  src/Reflection/ReflectionAttribute.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionConstant.php
  src/Reflection/ReflectionEnumCase.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/Reflection/ReflectionAttributeTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionConstantTest.php
  test/unit/Reflection/ReflectionEnumCaseTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement

#1225 Fixed mutation testing badge
  README.md
Labels: enhancement

#1226 Removed `ReflectionMethod::getAst()`, `getBodyAst()`, `getBodyCode()` and `getReturnStatementsAst()` to prevent memory leaks
  README.md
  docs/ast-extraction.md
  docs/features.md
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionAttribute.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionFunction.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionIntersectionType.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionNamedType.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/ReflectionUnionType.php
  test/compat/GetFunctionBody.phpt
  test/compat/ProduceAstForFunction.phpt
  test/unit/Fixture/Attributes.php
  test/unit/Fixture/Methods.php
  test/unit/Reflection/ReflectionAttributeTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionIntersectionTypeTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionUnionTypeTest.php
Labels: enhancement, BC break

#1229 Removed `ReflectionClass::getAst()` to prevent memory leaks
  src/Reflection/Exception/Uncloneable.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionEnum.php
  src/Reflection/ReflectionObject.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/Util/Visitor/ReturnNodeVisitor.php
  test/compat/CannotCloneReflection.phpt
  test/compat/ProduceAstForClass.phpt
  test/unit/Fixture/Enums.php
  test/unit/Reflection/Exception/UncloneableTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionEnumCaseTest.php
  test/unit/Reflection/ReflectionObjectTest.php
  test/unit/Util/Visitor/ReturnNodeVisitorTest.php
Labels: enhancement, BC break

#1231 `ReflectionClass::getConstant()`, `getConstants()` and `getImmediateConstants()` more consistent with methods and properties methods
  src/NodeCompiler/CompileNodeToValue.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionObject.php
  src/Reflection/StringCast/ReflectionClassStringCast.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/NodeCompiler/CompilerContextTest.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionAttributeTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/StringCast/ReflectionClassConstantStringCastTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
Labels: enhancement, BC break

#1230 Default PHP parser is not memoizing to prevent memory leaks
  src/BetterReflection.php
Labels: enhancement, BC break

#1233 `ReflectionClass::getMethod()` returns null when method does not exist
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: enhancement, BC break

#1234 Method names, property names etc could be only `non-empty-string`
  src/NodeCompiler/CompileNodeToValue.php
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionEnum.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionEnumCaseTest.php
  test/unit/Reflection/ReflectionEnumTest.php
  test/unit/Reflection/ReflectionFunctionAbstractTest.php
  test/unit/Reflection/ReflectionMethodTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Reflection/StringCast/ReflectionClassConstantStringCastTest.php
  test/unit/Reflection/StringCast/ReflectionMethodStringCastTest.php
  test/unit/Reflection/StringCast/ReflectionParameterStringCastTest.php
  test/unit/Reflection/StringCast/ReflectionPropertyStringCastTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement

#1235 Filter parameter for methods, properties and constants is always `int-mask-of`
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionClassConstant.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionProperty.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: enhancement, BC break

#1236 Improved return type of `Reflection*::getModifiers()`
  phpstan.neon
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionClassConstant.php
  src/Reflection/ReflectionMethod.php
  src/Reflection/ReflectionProperty.php
Labels: enhancement

#1240 Detection of circular references
  phpstan.neon
  src/Reflection/Exception/CircularReference.php
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/InvalidParents.php
  test/unit/Reflection/Exception/CircularReferenceTest.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement

#1238 Improved code coverage and mutation score
  infection.json.dist
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionObject.php
  src/Reflection/ReflectionProperty.php
  src/Reflection/ReflectionType.php
  src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php
  src/Util/FileHelper.php
  test/unit/BetterReflectionTest.php
  test/unit/Fixture/ConstantsToIgnore.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Fixture/ExampleClassExport.txt
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
  test/unit/Reflection/Adapter/ReflectionParameterTest.php
  test/unit/Reflection/Adapter/ReflectionTypeTest.php
  test/unit/Reflection/Annotation/AnnotationHelperTest.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/Reflection/ReflectionTypeTest.php
  test/unit/SourceLocator/Ast/FindReflectionsInTreeTest.php
  test/unit/SourceLocator/Type/AnonymousClassObjectSourceLocatorTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
  test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
Labels: enhancement

#1237 Fixed adapters compatibility
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionObjectTest.php
Labels: bug, reflection compatibility

#1241 Detection of interface extends circular references
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/InvalidInterfaceParents.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement

#1243 Some improvements for `ReflectionClass`
  src/Reflection/ReflectionClass.php
Labels: enhancement

#1245 Removed support for PHP4 style constructors
  src/Reflection/ReflectionMethod.php
  test/unit/Fixture/Php4StyleCaseInsensitiveConstruct.php
  test/unit/Fixture/Php4StyleConstruct.php
  test/unit/Fixture/Php4StyleConstructInNamespace.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: enhancement, BC break

#1246 Fixed `ReflectionNamedType::getClass()` for `self` defined in trait
  src/Reflection/ReflectionNamedType.php
  test/unit/Reflection/ReflectionNamedTypeTest.php
Labels: bug

#1247 Interface can have only public properties
  src/Reflection/ReflectionClass.php
Labels: enhancement

#1248 Increased minimum covered code mutations core to 100 %
  infection.json.dist
Labels: enhancement

#1250 PHP 8.2: Property in readonly class is readonly
  src/Reflection/ReflectionProperty.php
  test/unit/Fixture/ExampleClass.php
  test/unit/Reflection/ReflectionPropertyTest.php
Labels: bug

#1252 Optimise interface traversion in `ReflectionClass`
  src/Reflection/ReflectionClass.php
Labels: enhancement

#1255 Mark `ReflectionClass::getMethods()` compatible with other similar getters
  src/Reflection/Adapter/ReflectionClass.php
  src/Reflection/Adapter/ReflectionEnum.php
  src/Reflection/Adapter/ReflectionObject.php
  src/Reflection/ReflectionClass.php
  test/benchmark/PhpUnitTestCaseBench.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement, BC break

#1257 Less memory usage in `ReflectionMethod::withCurrentClass()`
  src/Reflection/ReflectionMethod.php
  test/unit/Reflection/ReflectionMethodTest.php
Labels: enhancement, BC break

#1258 Fixed return type of `ReflectionClass::getDefaultProperties()`
  src/Reflection/ReflectionClass.php
Labels: enhancement

#1256 Detection of circular references in constant, method and property getters
  src/Reflection/ReflectionClass.php
  src/Reflection/Support/AlreadyVisitedClasses.php
  test/unit/Fixture/InvalidTraitUses.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/Support/AlreadyVisitedClassesTest.php
Labels: enhancement
