Repository Roave/BetterReflection, pull requests merged in 2024-03, with the labels that each got.

#1396 Implement PHP Version dependent deprecations for constants
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement, dependencies

#1383 Support for final modifier in traits
  composer.json
  composer.lock
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/TraitFixtureWithFinal.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: enhancement

#1401 Support only PHP 8.2+
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  tools/composer.json
  tools/composer.lock
Labels: enhancement, dependencies

#1402 Move `PHPUnit` back to standard `composer.json`
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  infection.json.dist
  test/benchmark/PhpUnitTestCaseBench.php
  test/bootstrap.php
  test/unit/Reflection/ReflectionClassConstantTest.php
  tools/composer.json
  tools/composer.lock
Labels: enhancement, dependencies

#1404 PhpParser 5 & PhpUnit 11
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  phpbench.json
  phpunit.xml.dist
  psalm-baseline.xml
  src/BetterReflection.php
  src/NodeCompiler/CompileNodeToValue.php
  src/NodeCompiler/Exception/UnableToCompileNode.php
  src/Reflection/ReflectionClass.php
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionProperty.php
  src/SourceLocator/Ast/FindReflectionsInTree.php
  src/SourceLocator/Ast/Parser/MemoizingParser.php
  src/SourceLocator/Ast/Strategy/NodeToReflection.php
  src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/ClosureSourceLocator.php
  src/Util/GetLastDocComment.php
  test/unit/Fixture/ClassForSourceStubberExpected.php
  test/unit/Fixture/PHP81ClassForSourceStubberExpected.php
  test/unit/Fixture/PHP83ClassForSourceStubberExpected.php
  test/unit/Fixture/PHP8ClassForSourceStubberExpected.php
  test/unit/Reflection/Adapter/ReflectionAttributeTest.php
  test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
  test/unit/Reflection/Adapter/ReflectionClassTest.php
  test/unit/Reflection/Adapter/ReflectionEnumBackedCaseTest.php
  test/unit/Reflection/Adapter/ReflectionEnumTest.php
  test/unit/Reflection/Adapter/ReflectionEnumUnitCaseTest.php
  test/unit/Reflection/Adapter/ReflectionIntersectionTypeTest.php
  test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
  test/unit/Reflection/Adapter/ReflectionUnionTypeTest.php
  test/unit/Reflection/ReflectionClassTest.php
  test/unit/Reflection/ReflectionParameterTest.php
  test/unit/Reflection/ReflectionPropertyTest.php
  test/unit/SourceLocator/Ast/FindReflectionsInTreeTest.php
  test/unit/SourceLocator/Ast/Parser/MemoizingParserTest.php
  test/unit/SourceLocator/Ast/Strategy/NodeToReflectionTest.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
  test/unit/SourceLocator/Type/AbstractSourceLocatorTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
  test/unit/SourceLocator/Type/AutoloadSourceLocatorWithoutLoadedParserDependenciesTest.php
  test/unit/SourceLocator/Type/ComposerSourceLocatorTest.php
  tools/composer.json
  tools/composer.lock
Labels: enhancement, dependencies

#1408 Fix php version dependent constant deprecation
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement, dependencies

#1407 Kill startLine & endLine mutants
  psalm-baseline.xml
  src/Reflection/ReflectionFunctionAbstract.php
  src/Reflection/ReflectionParameter.php
  src/Reflection/ReflectionProperty.php
Labels: enhancement, dependencies

#1409 Remove unused dependency (roave/signature)
  composer.json
  composer.lock
Labels: enhancement, dependencies

#1413 Fix non-version dependent deprecations
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/Reflection/ReflectionConstantTest.php
Labels: bug

#1414 More efficient `ReflectionClass->getParentClass()`
  psalm-baseline.xml
  src/Reflection/ReflectionClass.php
Labels: enhancement

#1416 Prevent autoloading when determinig constant values
  src/SourceLocator/SourceStubber/PhpStormStubs/CachingVisitor.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: bug

#1418 Assert parsing PHPStorm stubs will never trigger autoload
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement
