Repository Roave/BetterReflection, pull requests merged in 2024-04, with the labels that each got.

#1419 Default value `null` does not make promoted property type nullable
  src/Reflection/ReflectionParameter.php
  test/unit/Fixture/NullableParameterTypeDeclarations.php
  test/unit/Reflection/ReflectionParameterTest.php
Labels: enhancement, reflection compatibility

#1424 Utilize more readable string functions
  src/Identifier/Identifier.php
  src/SourceLocator/Type/Composer/Psr/Psr0Mapping.php
  src/SourceLocator/Type/Composer/Psr/Psr4Mapping.php
  test/unit/SourceLocator/FileCheckerTest.php
Labels: enhancement

#1423 Update CI jobs to PHP 8.3
  .github/workflows/continuous-integration.yml
Labels: enhancement, dependencies

#1427 Use str_contains over strpos
  src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
  src/SourceLocator/Type/ClosureSourceLocator.php
Labels: enhancement
