Repository Roave/BetterReflection, pull requests merged in 2024-09, with the labels that each got.

#1446 Add missing entries to gitattributes
  .gitattributes
Labels: enhancement

#1445 Fix support of Enum stubs from PHPStorm
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
Labels: enhancement, dependencies

#1452 `ReflectionClass::getTraitAliases()` should maintain case
  psalm-baseline.xml
  src/Reflection/ReflectionClass.php
  test/unit/Fixture/TraitFixture.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug, reflection compatibility

#1448 Add fix for SplObjectStorage with next PHPStorm stubs
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
Labels: enhancement, reflection compatibility, dependencies
