Repository Roave/BetterReflection, pull requests merged in 2025-02, with the labels that each got.

#1482 Update all dependencies
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  src/Reflection/Adapter/ReflectionMethod.php
  src/Reflection/Adapter/ReflectionProperty.php
  src/Reflection/ReflectionPropertyHookType.php
  src/Reflection/StringCast/ReflectionClassStringCast.php
  src/Reflection/StringCast/ReflectionStringCastHelper.php
  src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
  src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
  src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
  src/SourceLocator/Type/AutoloadSourceLocator.php
  src/SourceLocator/Type/ClosureSourceLocator.php
  src/SourceLocator/Type/Composer/PsrAutoloaderLocator.php
  src/SourceLocator/Type/ComposerSourceLocator.php
  src/SourceLocator/Type/SingleFileSourceLocator.php
  tools/composer.json
  tools/composer.lock
Labels: enhancement, dependencies

#1486 Run PHPCS on PHP 8.4
  .github/workflows/continuous-integration.yml
Labels: enhancement

#1485 Fixed modifiers of trait method when method does not exist in current class
  psalm-baseline.xml
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#1487 Fixed property from interface implemented by trait
  src/Reflection/ReflectionClass.php
  test/unit/Reflection/ReflectionClassTest.php
Labels: bug

#1490 Update all non-major dependencies
  composer.json
  composer.lock
  tools/composer.json
  tools/composer.lock
Labels: dependencies

#1492 Upgrade to Psalm 6.8.6
  psalm.xml
  tools/composer.json
  tools/composer.lock
Labels: dependencies

#1493 Lock file maintenance
  test/unit/NodeCompiler/CompileNodeToValueTest.php
  test/unit/Reflection/ReflectionClassTest.php
  tools/composer.lock
Labels: dependencies
